---
- name: Provision web server
  hosts: webserver
  become: yes 
  vars:
    nginx_user: nginx
    nginx_group: nginx
    nginx_root: /var/www/html
    index: ./index.html

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
      become: yes

    - name: Create nginx group
      group:
        name: "{{ nginx_group }}"
        state: present
        system: yes

    - name: create nginx user
      user:
        name: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        state: present
        system: yes 
        shell: /bin/false 
        home: /var/cache/nginx 
        create_home: no 

    - name: Start and enable nginx
      systemd:
        name: nginx 
        state: started 
        enabled: yes

    - name: Create web root directory
      file:
        path: "{{ nginx_root }}"
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        mode: '0755'
    
    - name: Copy index.html
      ansible.builtin.copy:
        src: "{{ index }}"
        dest: "{{ nginx_root }}/index.html"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        mode: '644'





      
